image:
  repository: europe-docker.pkg.dev/gardener-project/releases/github-oidc-federation
  tag: latest
gateway:
  className: ""
  annotations: {}
  proxyImage: {}  # optional: repository and tag to override the default envoy proxy image
  loadBalancerIP: ""  # optional: pin the LB to a specific IP
httpRoute:
  hosts: []
networkPolicy:
  gatewayController:
    enabled: true
    namespace: envoy-gateway-system
