hpa:
  minReplicas: 2
  maxReplicas: 5
  cpu:
    averageUtilization: 80
  memory:
    averageUtilization: 80
image:
  repository: europe-docker.pkg.dev/gardener-project/releases/github-oidc-federation
  tag: latest
ingress:
  annotations: {}
  class: nginx
  hosts: []
