image:
  repository: europe-docker.pkg.dev/gardener-project/releases/github-oidc-federation
  tag: latest
gateway:
  className: ""
httpRoute:
  annotations: {}
  hosts: []
networkPolicy:
  gatewayController:
    enabled: true
    namespace: envoy-gateway-system
