#!/usr/bin/env bash
set -eu

# usage: $1: <src-dir>

src_dir="${1:-"$(readlink -f "$(dirname "${0}")/..")"}"

linters_with_findings=()

if ! which ruff &>/dev/null; then
    pip3 install --break-system-packages ruff >/dev/null
fi

echo 'running ruff check'
if ruff check "${src_dir}"; then
    echo 'ruff check succeeded'
else
    echo 'ruff check yielded findings (see above)'
    linters_with_findings+=('ruff-check')
fi

echo 'running ruff format --check'
if ruff format --check "${src_dir}"; then
    echo 'ruff format succeeded'
else
    echo 'ruff format yielded findings (see above)'
    linters_with_findings+=('ruff-format')
fi

if ! which bandit &>/dev/null; then
    pip3 install --break-system-packages bandit >/dev/null
fi

echo "running bandit (sast-linter) - extra-args: ${bandit_extra_args:-}"
if bandit \
    --configfile "${src_dir}/pyproject.toml" \
    --recursive \
    "${src_dir}" ${bandit_extra_args:-}; then
    echo "bandit exited without error"
else
    linters_with_findings+=('bandit')
fi

if [ ${#linters_with_findings[@]} == 0 ]; then
    echo "all linters exited without findings"
    exit 0
else
    echo "Error: the following linters yielded findings"
    echo ""
    for l in "${linters_with_findings[@]}"; do
        echo " - ${l}"
    done

    exit 1
fi
