apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}
spec:
  gatewayClassName: {{ required "gateway.className is required" .Values.gateway.className }}
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: github-oidc-federation-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: github-oidc-federation
  {{- if default dict (.Values.httpRoute).annotations }}
  annotations:
    {{- range $annotation, $value := .Values.httpRoute.annotations }}
    {{ $annotation }}: {{ $value }}
    {{- end }}
  {{- end }}
spec:
  parentRefs:
    - name: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
  {{- if default list (.Values.httpRoute).hosts }}
  hostnames:
    {{- range $host := .Values.httpRoute.hosts }}
    - {{ $host }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: github-oidc-federation
          port: 3000
  {{- end }}
