apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  # select all pods in the namespace
  podSelector: {}
  # deny all traffic
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-from-github-oidc-federation
spec:
  podSelector:
    matchLabels:
      role: github-oidc-federation
  policyTypes:
    - Egress
  egress:
    - {} # Allows all egress traffic to any destination and port
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-github-oidc-federation
spec:
  podSelector:
    matchLabels:
      role: github-oidc-federation
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 3000
      {{- if .Values.networkPolicy.ingressController.enabled }}
      from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: nginx-ingress
          podSelector:
            matchLabels:
              app.kubernetes.io/component: controller
      {{- end }}
    - ports:
        - protocol: TCP
          port: 3000
      from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
          podSelector:
            matchLabels:
              role: github-oidc-federation
