apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-oidc-federation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-oidc-federation-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-oidc-federation-pod-reader
subjects:
  - kind: ServiceAccount
    name: github-oidc-federation
roleRef:
  kind: Role
  name: github-oidc-federation-pod-reader
  apiGroup: rbac.authorization.k8s.io
