name: test-oidc

on:
  push:
    branches:
      - refactor-oidc

permissions:
  id-token: write

jobs:
  token-exchange:
    runs-on: ubuntu-latest
    steps:
      - name: Request OIDC token and call token-exchange
        env:
          ENDPOINT: https://github-oidc-federation.ingress.test-clusti.garden-ci.shoot.live.k8s-hana.ondemand.com/token-exchange
        run: |
          TOKEN=$(curl -sSfL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=github-oidc-federation" \
            | jq -r '.value')

          RESPONSE=$(curl -sSf -X POST "$ENDPOINT" \
            -H "Content-Type: application/json" \
            -d '{
              "token": "'"$TOKEN"'",
              "host": "github.com",
              "organization": "gardener",
              "permissions": {
                "contents": "write",
                "pull_requests": "write",
                "workflows": "write"
              },
              "repositories": ["alpine-conntrack"]
            }')

          echo "$RESPONSE" | jq -e '.token != null' > /dev/null
          echo "Success"
